background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 10
}

input-field {
    monitor =
    size = 340, 54
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    outer_color = rgba(7dcfffcc)
    inner_color = rgba(16161fee)
    font_color = rgba(c0caf5ff)
    check_color = rgba(7aa2f7cc)
    fail_color = rgba(f7768ecc)
    fade_on_empty = true
    placeholder_text = <i>unlock</i>
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 68
    font_family = Fira Code
    color = rgba(c0caf5ff)
    halign = center
    valign = center
    position = 0, 120
}

label {
    monitor =
    text = cmd[update:3600000] echo "$(date '+%A, %B %d')"
    font_size = 20
    font_family = Fira Code
    color = rgba(9aa5ceff)
    halign = center
    valign = center
    position = 0, 70
}
